### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by bgulla** [klucar/accumulocraft#1]
yes.

**Comment by klucar** [comment]
true

**Comment by bgulla** [comment]
+1

**Comment by bgulla** [comment]
+1

On Thu, Dec 3, 2015 at 6:59 PM, Jim Klucar <notifications@github.com> wrote:

> true
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klucar/accumulocraft/issues/1#issuecomment-161828564>.
>



-- 
Brandon

**Comment by klucar** [comment]
obviously
